version: '3.8'
services:
  backend:
    image: evercoinx/faraway:nft-collection-deployer-backend
    ports:
      - "4000:4000"
    restart: unless-stopped

  frontend:
    image: evercoinx/faraway:nft-collection-deployer-frontend
    ports:
      - "3000:3000"
    restart: unless-stopped
