export const TEST_WALLET_ADDRESS = '0x7E87B06eca3B24DEA74fE87e7F2715aE395dF615'

export const DEPLOY_COLLECTION_TEST_DATA = {
  COLLECTION_NAME: 'TestCollection',
  COLLECTION_SYMBOL: 'TST',
  TOKEN_URI: 'collection_uri',
}

export const MINT_NFT_TEST_DATA = {
  COLLECTION_ADDRESS: '',
  RECIPIENT_ADDRESS: TEST_WALLET_ADDRESS,
  TOKEN_ID: '1',
}
